### ISSUE TITLE
Error installing node since 2.2.0

### ISSUE THREAD

**Issue by kyriacos** [nodenv/node-build#120]
I keep seeing this in the terminal `grep: /usr/local/Cellar/node-build/2.2.0/bin/../package.json: No such file or directory` whenever i run `node-build --version`.

Also tried on a different machine we started getting failures in installing node 5.6.0.

Whenever we ran the `nodenv install 5.6.0` or `node-build` equivalent command we got the message again (`grep: /usr/local/Cellar/node-build/2.2.0/bin/../package.json: No such file or directory`) and it said could not copy binary file, try installing from source (-c).

Tried that too and it didn't work, so we switched back to 2.1.5 and everything worked fine.

Thanks!

**Comment by jawshooah** [comment]
This occurs because we don't currently include `package.json` when installing via Homebrew. There are a few potential solutions:

- Install `package.json` in the [node-build formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/node-build.rb) after running `install.sh`
- Install `package.json` in `install.sh`, though `PREFIX` defaults to `/usr/local`, which is not a directory we want to pollute
- Make `NODE_BUILD_VERSION` a constant rather than parsing `package.json`. This means bumping the version in two places, `package.json` and `bin/node-build`, but this should be easy by adding a `version` script, which `npm version` will execute [after bumping the version in `package.json`](https://docs.npmjs.com/cli/version)

@jasonkarns, what do you think?

**Comment by jasonkarns** [comment]
welp that was a :facepalm:

definitely need to restore the NODE_BUILD_VERSION constant in ruby-build and add a version script.

let's first get the constant put back in so that node-build isn't broken. we can do the script later. @jawshooah are you able to do that soon? 

relevant:

193d2c4ce4b8654fa67b6fb2af670bf2bd426a45
581a3100a296e75e5512f40d70c0400abb28081f
9dee088fa01164be633532df960ae20cd3e78cca
ec5651e9b57e61277e93fcab1bb10e7479ecacf9

**Comment by jawshooah** [comment]
> are you able to do that soon?

Sure, I can pump that out in just a bit.

**Comment by jasonkarns** [comment]
released as v2.2.1

**Comment by jasonkarns** [comment]
@kyriacos can you confirm this is fixed via homebrew, once homebrew updates the node-build formula? (awaiting: https://github.com/Homebrew/homebrew/pull/49529)

**Comment by kyriacos** [comment]
@jasonkarns just updated! Works as expected now.

@jawshooah @jasonkarns thanks to the both of you for getting the update out so fast.
