### ISSUE TITLE
Unable to install 4.x-dev or 4.x-next

### ISSUE THREAD

**Issue by JaKXz** [nodenv/node-build#143]
```
$ nodenv install 4.x-dev
Cloning https://github.com/nodejs/node.git...
Installing 4.x-dev...

BUILD FAILED (OS X 10.11.4 using node-build 2.2.6)

Inspect or clean up the working tree at /var/folders/cg/tn3c27yx4mv4c06p9gh19yzh0000gn/T/node-build.20160406120148.7277
Results logged to /var/folders/cg/tn3c27yx4mv4c06p9gh19yzh0000gn/T/node-build.20160406120148.7277.log

Last 10 log lines:
                 'v8_enable_i18n_support': 0,
                 'v8_no_strict_aliasing': 1,
                 'v8_optimized_debug': 0,
                 'v8_random_seed': 0,
                 'v8_use_snapshot': 'true',
                 'want_separate_host_toolset': 0,
                 'xcode_version': '7.3'}}
creating  ./config.gypi
creating  ./config.mk
make: *** empty string invalid as file name.  Stop.
```

I get the same errors for both, using `nodenv` v1.0.0 - please let me know if I can provide any other information. I have `eval "$(nodenv init -)"` in my `~/.bash_profile`, and I've restarted my terminal and seen no errors in its execution, so I'm not sure what's going on.

**Comment by jasonkarns** [comment]
Do you specifically want to build (unreleased) node versions from source?

Generally, it's recommended to install the pre-build binaries that nodejs distributes. Right now, for LTS that's 4.4.2 and for Stable that's 5.10.1.

`nodenv install 4.4.2` will install the distributed binary (if one matches your system) and only falls back to compiling from source as a last resort. (or if requested with `--compile`)

So if the goal is to get a recent version of node 4 installed, I highly recommend this, instead of attempting to compile unreleased versions.

If you're intent on debugging the compilation errors, I would take this to nodejs, as this looks suspiciously like an error that has occurred before: https://github.com/nodejs/node/issues/2839

Also note, you can pass `--verbose` so that node-build prints the whole log, rather than just the last 10 lines. (Or, of course, just `cat` out the log in full.) I imagine that the node team will want a full output.

**Comment by JaKXz** [comment]
@jasonkarns thanks for the response - ideally, I'd be able to get the latest LTS release and `nodenv` would keep my environment up to date with that. For now I could just pin to a specific version.

**Comment by jasonkarns** [comment]
The 4.x-dev and 4.x-next build definitions are pulling from git, so they
are pre-release edge builds.

We don't currently have any build definitions that pin to latest releases.
I don't think we've had the discussion within nodenv, but I believe the
rbenv team considers this sort of an antipattern, as running the same
command on two different days could get you different node versions.

I'm going to open an issue to discuss whether we want some kind of 'latest'
build def. Also see nodenv-aliases that will create a major.minor version
alias that is automatically updated to point to the latest patch release
for whichever nodes you have installed. The act of actually installing the
latest nodes is still manual, but nodenv-aliases means you don't have to
update any `.node-version` files or NODENV_VERSION var.

**Comment by JaKXz** [comment]
Thanks! Shall I close this issue or leave it to you? :)

**Comment by jasonkarns** [comment]
Opened #145 for discussion of "latest" aliases.
