### ISSUE TITLE
how do I force node-build to use homebrew openssl?

### ISSUE THREAD

**Issue by AlJohri** [nodenv/node-build#281]
originally from https://github.com/nodenv/nodenv/issues/78

for example, in ruby:

```
RUBY_CONFIGURE_OPTS=--with-openssl-dir=/usr/local/opt/openssl rbenv install -s "$ruby_version"
```

in python:

```
CFLAGS=-I/usr/local/opt/openssl/include LDFLAGS=-L/usr/local/opt/openssl/lib pyenv install -s "$python_version"
```

trying to figure out how to do this with nodenv. thanks!

**Comment by jasonkarns** [comment]
I would love to have the option to use homebrew's openssl similar to how [ruby-build](https://github.com/rbenv/ruby-build) does it. However, I don't know what the `configure` option needs to be in order to dynamically link during node compilation.

node-build (and therefore, the nodenv-install plugin as well) supports the same env vars as it's parent ([ruby-build](https://github.com/rbenv/ruby-build)). So `NODE_CONFIGURE_OPTS`, `NODE_MAKE_OPTS` and `NODE_MAKE_INSTALL_OPTS` all work. (see [readme](https://github.com/nodenv/node-build/blob/master/README.md#special-environment-variables)) The trick would be finding what the exact option needs to be, and that is determined by [nodejs](https://github.com/nodejs/node) itself.

I'm going to leave this ticket open in the hopes that someone digs through node's compilation options and documents the flag. (Which would allow node-build to make an option for linking against homebrew's openssl.)

**Comment by jasonkarns** [comment]
(I'd start by checking for the available ssl/openssl flags here: https://github.com/nodejs/node/blob/master/configure)

**Comment by jasonkarns** [comment]
@AlJohri any luck?

**Comment by jasonkarns** [comment]
The openssl configure options are here: https://github.com/nodejs/node/blob/b4f0a18b5a717b10d2d1c98e7aba85f0ac33aa68/configure.py#L254-L274

In particular, there is `--shared-openssl-libpath`.

So presumably, the following should work:

```
NODE_CONFIGURE_OPTS=--shared-openssl-libpath=/usr/local/opt/openssl nodenv install "$node_version"
```

The above is untested but something similar ought to work. If anyone tries and confirms, please post back here.
