### ISSUE TITLE
Accept version with 'v' prefix

### ISSUE THREAD

**Issue by bostonaholic** [nodenv/node-build#307]
I should be able to install node versions with the 'v' prefix. e.g.

```
$ node-build v8.5.0 ~/local/node-8.5.0
```

This allows my `.node-version` file to have `v8.5.0` in it. This is consistent with the output of

```
$ node --version
v8.5.0
```

**Comment by jasonkarns** [comment]
So here's the story:

`nodenv-install` figures out which version to install based on the argument, or uses `nodenv-local` as a _fallback_.  https://github.com/nodenv/node-build/blob/master/bin/nodenv-install#L118-L124

The version names passed as an argument (or derived per above) must exactly correspond to a definition file somewhere in the definitions path. (The ones built-in to node-build under `/share/node-build` plus `NODE_BUILD_DEFINITIONS`)

The way that nodenv allows fuzzy names for _activating_ nodes (with/without "v" or "node-" prefix) is be first checking if the specified version exists, then attempting all the supported fuzzy alternatives.

So what we have here is a catch-22. The fuzzy logic depends on the version being installed, and the installation requires exact matching.

Further complicating this... if we duplicated the fuzzy matching, it would need to occur in the nodenv-install plugin _prior_ to invoking node-build. However, the logic for looking up the definition based on the version name lives in node-build itself.

So no quick fix.

Best I can recommend for now is doing `nodenv install <exact-version-name>` rather than relying on `nodenv-install` to pull from nodenv-local (or alternatively, ensure the `.node-version` file uses exact names, though I imagine you want that to be compatible with team members? Perhaps the other team members' tools support exact names?)

**Comment by jasonkarns** [comment]
@bostonaholic over a year later, I'm giving this a shot...

Since node-build is the core "do exactly what I say" utility, I don't think I want it to do any guessing or re-resolving of the definition or version name. However, the nodenv-install plugin, which is already more aware of the expected conventions, _can_.

So `node-build` would still take in an exact path to  a definition, and require the exact prefix/path/name for where to dump the built node.
But `nodenv install X` for `1.0.0`/`v1.0.0`/`node-1.0.0`/`node-v1.0.0` would all match the definition for `1.0.0`.

The question is: would you expect the final installed version to match the name given to `nodenv install` (ie, with the v/node-/node-v prefix) ? Or would you expect the final version name to match the derived name when it finds a matching definition file?

I believe either one would technically work, since it would use the same fuzzy name matching as nodenv itself does when activating a node. Which means regardless if the final version name has the prefixes, it would be found.

My initial opinion is that only the definition file name should be fuzzy-matched; the final version name should match the initial explicit value. This approach is the simplest for the code (it won't require multiple rounds of "existing version checking"). The down side is that you could _potentially_ end up with duplicate nodes installed, essentially.

Say you already have node `8.0.0` installed. Then you `NODENV_VERSION=v8.0.0 nodenv install`. That would result in node-build being executed with definition file for `8.0.0`, but installing it as `v8.0.0` resulting in both nodes: `8.0.0` and `v8.0.0`. Of course, it would still be activated with `v8.0.0`, but the activation logic only _removes_ the various prefixes. Thus `v8.0.0` would only ever be activated by using that precise name. Whereas `8.0.0` could be activated by `8.0.0`, `node-8.0.0` or `node-v8.0.0`. Tradeoffs!

**Comment by bostonaholic** [comment]
I would expect both `v8.0.0` and `8.0.0` to resolve to the same "version" of node such that all packages installed for one is also accessible to the other. Similar to `rbenv`.

**Comment by jasonkarns** [comment]
`rbenv` doesn't do this, though. This would be a brand new feature for both rbenv and nodenv:

```
$ rbenv install v2.5.0
ruby-build: definition not found: v2.5.0

See all available versions with `rbenv install --list'.

If the version you need is missing, try upgrading ruby-build:

  brew update && brew upgrade ruby-build
```

Now, `nodenv version` will resolve `v1.2.3` as `1.2.3` if `1.2.3` is _already installed_. And both `{nodenv,rbenv} version` will resolve `{node,ruby}-1.2.3` as `1.2.3` if `1.2.3` is already installed. But ruby-build won't auto-resolve to the prefix-less version when installing a new version. It still expects the version name to map to an explicit existing definition file.

Hence why this feature is breaking new ground. Need to decide what to do if someone manually attempts `nodenv install v1.2.3` if `1.2.3` is already installed.

The way #455 solves this is to hook into the  "after install" hook that node-build already has. If the build _fails_ due to a missing definition file (because none of the definition files have v/node-/node-v prefixes), then it will strip the prefix and re-run the install command. Since it re-runs the command with the prefix stripped, the name of the version that actually gets installed will be the prefix-less variant. Which also means any conflict with existing version will trigger the same Y/N prompt as if you initiate an install with conflicting version by hand.

**Comment by bostonaholic** [comment]
OK, this is very weird. I could have sworn, because it's why I created the issue in the first place, that `v2.6.0` in a `.ruby-version` file worked. I just tested it and it definitely does not. 🤷‍♂️

**Comment by jasonkarns** [comment]
😜 

It (`ruby-` prefix only) definitely works to _pick_ a version if the version is already installed: https://github.com/rbenv/rbenv/blob/59785f6762e9325982584cdab1a4c988ed062020/libexec/rbenv-version-name#L28-L32

It's just the installation that can't handle any aliasing. But now nodenv does! (#455  merged to master but not released yet)
