### ISSUE TITLE
Defs for nodejs-mobile

### ISSUE THREAD

**Issue by jasonkarns** [nodenv/node-build#415]
https://github.com/janeasystems/nodejs-mobile

**Comment by mohlsen** [comment]
Does is make sense for node-build to install nodejs-mobile?  Since the deployment target is iOS or android, what would be the purpose of installing it on a local development system (if it is even possible).

As an alternative would be more beneficial for node-build to install the equivalent version of [nodejs/node-chakracore](https://github.com/nodejs/node-chakracore) from which nodejs-mobile is based (if it is not already supported)?  That way when running locally for testing, you can run on a desktop using the equivalent version of node.

thoughts?

**Comment by jasonkarns** [comment]
I believe I agree. When I started the process here, I thought it might be beneficial so that one could compile the libraries from source. However, I suppose it's not often anyone needs to do that, so there probably isn't much value in it. (And those who do compile from source probably wouldn't need or use node-build to do it.)

And since, as you said, the precompiled binaries are only for mobile, I think I agree. Gonna think on it just a bit more, but probably closing this. Thanks for the input!

**Comment by jaimecbernardo** [comment]
Regarding `nodejs-mobile`, it might be useful for people who are using Android devices to run node as an executable in command line utilities like Termux.
While nodejs-mobile is known to have been used like this, it's not a common scenario and is not directly supported by the project.

**Comment by jasonkarns** [comment]
@mohlsen thanks! chakracore is already supported OOTB: `nodenv install chakracore-X.Y.Z`

@jaimecbernardo that's good to know. i'm betting in scenarios like that, they would just pull the binary from https://github.com/janeasystems/nodejs-mobile/releases ? more to the point, i'm guessing they wouldn't need to run multiple versions and switch between them? That's the primary goal of nodenv is managing multiple nodes. while node-build's primary goal is to easily compile node, it's secondary goal is just to install nodes for nodenv. Sounds like even the few people who do run nodejs-mobile via termux wouldn't even use node-build to get it?

**Comment by jasonkarns** [comment]
Thanks all!

**Comment by jasonkarns** [comment]
@jaimecbernardo closing for now, but if the nodejs-mobile team finds a future use-case for installing nodejs-mobile binaries (to be executed as an runtime or repl), i'd be happy to have node-build learn how to do it
