### ISSUE TITLE
Install issue likely related to macOS 11

### ISSUE THREAD

**Issue by chandlerroth** [nodenv/node-build#623]
Hello! I'm running macOS 11 (or 10.16 beta 2), and having issues updating node-build via homebrew. Here's an excerpt of the commands I ran, and their output:

```
brew update && brew upgrade node-build

==> Upgrading 1 outdated package:
node-build 4.7.2 -> 4.9.1
==> Upgrading node-build 4.7.2 -> 4.9.1 
==> Downloading https://github.com/nodenv/node-build/archive/v4.9.1.tar.gz
Already downloaded: /Users/chandler/Library/Caches/Homebrew/downloads/7a345404eb169f2c4c659090d0d15a11454eed5dae97ec738d6921b09f242824--node-build-4.9.1.tar.gz
Error: An exception occurred within a child process:
  NoMethodError: undefined method `path' for nil:NilClass
Did you mean?  paths
```

I was able to upgrade other formulae with homebrew successfully.

**Comment by jasonkarns** [comment]
That's a ruby error which means it's almost definitely an error within homebrew itself. It's possible that homebrew has changed something in their formula API, but I doubt it.

A quick search for that error message on homebrew-core indicates it is affecting other formulae (in core) as well as issue on the main brew repo.

https://github.com/Homebrew/homebrew-core/issues/57913
https://github.com/Homebrew/brew/issues/7864
https://github.com/Homebrew/brew/issues/7803

Closing for now since homebrew doesn't yet support Big Sur.

**Comment by chandlerroth** [comment]
As a follow up, I discovered that after installing the "Command Line Tools for Xcode 12 beta" from https://developer.apple.com/download/more/ this issue was resolved -- I've successfully updated node-build to v4.9.1. 

Thanks @jasonkarns for taking the time to respond!

**Comment by jasonkarns** [comment]
Thanks for sharing your solution!
